version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    voulumes: 
      - ./:/home/app
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=buggy-api
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:

